version: "3.5"
services: 
    tensorflow-echo-dl:
        build: 
            context: .
            dockerfile: Dockerfile
        image: tensorflow_echo_dl:1
        volumes:
            - ../logs:/logs
            - ../data:/data
            - ../src:/src
            - ../saved:/saved
        command: python train.py -b 1 -s 1000 --epochs 4 -p 10 -l 0.001
        user: $CURRENT_UID
