version: "3.5"
services: 
    tensorflow-echo-dl:
        build: 
            context: .
            dockerfile: Dockerfile
        image: tensorflow_echo_dl:1
        volumes:
            - ../logs:/logs
            - ../data:/data
            - ../src:/src
        command: python train.py -b 16 -s 1000 -e 200
        user: tensorflow:tensorflow
